version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: vilnius_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-vilnius_support}
      POSTGRES_USER: ${DB_USER:-vilnius_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secure_password}
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/backups:/backups
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - vilnius_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-vilnius_user} -d ${DB_NAME:-vilnius_support}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management (development only)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vilnius_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@vilnius.lt}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin123}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - vilnius_network
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - development  # Only start with --profile development

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  vilnius_network:
    driver: bridge