[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments]
  [environments.production]
  variables = [
    "NODE_ENV=production",
    "PORT=3002"
  ]
  
  [environments.development]
  variables = [
    "NODE_ENV=development",
    "PORT=3002"
  ]
