[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "NODE_ENV=production node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "vilnius-backend"
source = "."

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[[plugins]]
name = "postgresql"