[[services]]
name = "app"
source = "."

[services.build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[services.deploy]
startCommand = "node server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "database"
plugin = "postgresql"