#!/bin/bash

echo "🔧 Docker Cleanup and Restart Script"
echo "===================================="
echo ""
echo "This script will help clean up stuck Docker processes"
echo ""

echo "1. First, try to stop Docker Desktop and restart it manually"
echo "2. Then run these commands:"
echo ""
echo "# Force remove stuck containers:"
echo "docker rm -f vilnius-backend vilnius-postgres 2>/dev/null"
echo ""
echo "# Clean up Docker system:"
echo "docker system prune -af --volumes"
echo ""
echo "# Kill buildkit if stuck:"
echo "docker rm -f $(docker ps -aq --filter name=buildx_buildkit) 2>/dev/null"
echo ""
echo "3. After cleanup, start fresh:"
echo "docker-compose build --no-cache"
echo "docker-compose up -d"
echo ""
echo "Alternative: Use docker-compose without buildx:"
echo "COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=0 docker-compose build"